### ISSUE TITLE
getting papers list doesn't work appropriately 

### ISSUE THREAD

**Issue by deep-diver** [paperswithcode/paperswithcode-client#12]
I have tried querying 
`https://paperswithcode.com/api/v1/papers/?title=generative+adversarial+networks`

and it returns entries sorted by the publishing date not by the most relevant orders.

I have also tried with different parameters `q`, and it didn't work either. Actually, `title` and `q` performs the same behaviour. 

can you please check @alefnula ?

**Comment by alefnula** [comment]
Fixed and released in `0.2.1` version of [`paperswithcode-client`](https://pypi.org/project/paperswithcode-client/0.2.1/).
