### ISSUE TITLE
Error in task paper listing

### ISSUE THREAD

**Issue by paperswithcode-user** [paperswithcode/paperswithcode-client#15]
I have tried to use the `client.task_paper_list()` to obtain the papers for different tasks, but some of them yield the following error:

`ValidationError(400: Request validation error.)`

As an example, I printed the number of papers or an error message for the tasks listed for the query 'monocular', with the following output:

```
3d-object-detection-from-monocular-images: 5
indoor-monocular-depth-estimation: 3
Error for monocular-3d-human-pose-estimation
Error for monocular-3d-object-detection
monocular-3d-object-localization: 3
monocular-cross-view-road-scene-parsing-road: 1
monocular-cross-view-road-scene-parsing: 1
monocular-depth-estimation: 283
monocular-visual-odometry: 46
```

I verified on the webpage that these tasks have papers associated with them.

**Comment by alefnula** [comment]
Fixed and released in `v0.3.1`.
