### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by andre-fu** [paperswithcode/paperswithcode-client#8]
Hello, I was hoping to get some better documentation for this API. While it's a great resource it seems that its focused on getting SOTA updated comparisons. 

My goal was to get all the data from the [NAS ImageNet classification page ](https://paperswithcode.com/sota/neural-architecture-search-on-imagenet) and recreate a similar graph to the one on top but with some additional data. Unfortunately, I don't seem to see a way of doing this though the API. It even looks like I'd have to actually go an scrape the page itself for the desired data (but then I'm missing the release date which is only shown as year). 

Some additional documentation would be really helpful for me and those in the future trying to simply get specific data instead of doing SOTA comparisons. 

If its currently possible to do what I'm requesting please let me know! Thank you!

**Comment by rstojnic** [comment]
@andre-fu sorry the library is still in beta, so some functionality is still not entirely working. However, you should be able to get the results programmatically by just doing:

```
curl -X GET "https://paperswithcode.com/api/v1/evaluations/neural-architecture-search-on-imagenet/results/"
```

(this is the first page, add ?page=2, ?page=3 etc for the full results)

You can also see more API docs here: https://paperswithcode.com/api/v1/docs/

Hope this helps!
