### ISSUE TITLE
HttpClientTimeout(500: Timeout exceeded)

### ISSUE THREAD

**Issue by zcyzhuangzhou** [paperswithcode/paperswithcode-client#9]
First, I have created an API token.
Next, I want to query papers by title using this code:
`from paperswithcode import PapersWithCodeClient`
`client = PapersWithCodeClient(token="my_token")`
`papers = client.paper_list(q=title)`

but I got HttpClientTimeout error:
> tea_client.errors.HttpClientTimeout: HttpClientTimeout(500: Timeout exceeded)

Is there any way to prevent read timeout, or is it possible to modify the value of timeout?

**Comment by deep-diver** [comment]
looks like `q` parameter does not work for now

**Comment by alefnula** [comment]
Fixed, will be released tomorrow as version `0.2.0`

**Comment by deep-diver** [comment]
Thanks for the quick action!
